# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_tax', '0003_taxrule_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrule',
            name='shops',
            field=models.ManyToManyField(blank=True, to='shuup.Shop'),
        ),
    ]
