# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 15:26
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import shuup.core.fields
import shuup.core.models._payments
from django.db.utils import IntegrityError


def copy_currency(apps, schema_editor):
    Payment = apps.get_model('shuup', 'Payment')

    for obj in Payment.objects.all():
        try:
            obj.currency = obj.order.currency
            obj.save()
        except (ObjectDoesNotExist, IntegrityError):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0028_displayunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=shuup.core.fields.CurrencyField(null=True, max_length=4),
            preserve_default=False,
        ),
        migrations.RunPython(copy_currency),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=shuup.core.fields.CurrencyField(null=False, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expected_amount_value',
            field=shuup.core.fields.MoneyValueField(decimal_places=9, default=0, max_digits=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_payments', to='shuup.Payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=shuup.core.fields.UnsavedForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='shuup.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='psp_reference',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='state',
            field=enumfields.fields.EnumIntegerField(default=0, enum=shuup.core.models._payments.PaymentStates),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=shuup.core.models._payments.PaymentTypes),
        ),
    ]
