# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0029_auto_20170812_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modification_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modification_children', to='shuup.Product'),
        ),
    ]
