# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_freeproductline_quantity_to_quantityfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
